name: Run Notebooks on Trigger

# Trigger workflow when colab_trigger.txt is created/updated
on:
  push:
    paths:
      - colab_trigger.txt
    branches:
      - main

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbclient nbformat requests

      # 4. Execute all notebooks with logging
      - name: Run Notebooks
        run: python run_notebooks.py

      # 5. Delete trigger file after notebooks run
      - name: Delete Trigger File
        env:
          HUB_PAT: ${{ secrets.HUB_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          # Use PAT for push
          git remote set-url origin https://$HUB_PAT@github.com/${{ github.repository }}.git
          git rm colab_trigger.txt
          git commit -m "Remove trigger after workflow run"
          git push origin main
