name: Run Notebooks on Trigger

on:
  push:
    paths:
      - colab_trigger.txt
    branches:
      - main

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython nbclient nbformat requests

      # 4. Execute all notebooks and log outputs
      - name: Execute Notebooks
        run: |
          for nb_file in $(find . -name "*.ipynb"); do
            echo "➡️ Running $nb_file"
            NB_PATH="$nb_file" python3 - <<'PYTHON_EOF'
import os
import sys

nb_file = os.environ['NB_PATH']

try:
    import nbformat
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "nbformat"])
    import nbformat

try:
    from nbclient import NotebookClient
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "nbclient"])
    from nbclient import NotebookClient

with open(nb_file) as f:
    nb = nbformat.read(f, as_version=4)

client = NotebookClient(nb, timeout=600, kernel_name="python3", allow_errors=False)
try:
    client.execute()
    print(f"✅ Successfully executed {nb_file}")
except Exception as e:
    print(f"⚠️ Error executing {nb_file}: {e}")
    sys.exit(1)
PYTHON_EOF
          done

      # 5. Delete trigger file after run
      - name: Delete Trigger File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git rm colab_trigger.txt
          git commit -m "Remove trigger after workflow run"
          git push origin main
