name: Run Notebooks on Trigger

on:
  push:
    paths:
      - colab_trigger.txt
    branches:
      - main

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython nbclient nbformat requests

      - name: Execute Notebooks
        run: |
          for nb in $(find . -name "*.ipynb"); do
            echo "➡️ Running $nb"
            python - <<PYTHON
import nbformat
from nbclient import NotebookClient

with open("$nb") as f:
    nb = nbformat.read(f, as_version=4)

client = NotebookClient(nb, timeout=600, kernel_name="python3", allow_errors=False)
client.execute()
PYTHON
          done

      - name: Delete Trigger File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git rm colab_trigger.txt
          git commit -m "Remove trigger after workflow run"
          git push origin main
