name: Run Notebooks on Trigger

on:
  push:
    paths:
      - colab_trigger.txt
    branches:
      - main

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython nbclient nbformat requests

      # 4. Execute notebooks with detailed logging
      - name: Execute Notebooks with Logs
        run: |
          for nb in $(find . -name "*.ipynb"); do
            echo "➡️ Running $nb"
            python - <<'EOF'
import nbformat
from nbclient import NotebookClient
from nbclient.exceptions import CellExecutionError
import sys

nb_path = "$nb"
with open(nb_path) as f:
    nb = nbformat.read(f, as_version=4)

client = NotebookClient(nb, timeout=600, kernel_name="python3")

try:
    for i, cell in enumerate(nb.cells):
        if cell.cell_type == "code":
            print(f"\n🔹 Running cell {i}:\n{cell.source}\n")
            client.execute_cell(cell, i)
            # print outputs
            for output in cell.get("outputs", []):
                if output.output_type == "stream":
                    print(output.text)
                elif output.output_type == "execute_result":
                    print(output["data"].get("text/plain", ""))
                elif output.output_type == "error":
                    print("❌ ERROR:", output.evalue)
    print(f"✅ Finished running {nb_path}")
except CellExecutionError as e:
    print(f"⚠️ Notebook execution failed: {e}")
    sys.exit(1)
EOF
          done
