name: Run Notebooks on Trigger

# Trigger workflow when colab_trigger.txt is created/updated
on:
  push:
    branches:
      - main
    paths:
      - colab_trigger.txt

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython nbclient nbformat requests

      # 4. Run all notebooks in repo and log output
      - name: Execute Notebooks
        run: |
          for nb in $(find . -name "*.ipynb"); do
            echo "➡️ Running $nb"
            python - <<EOF
import nbformat
from nbclient import NotebookClient

with open("$nb") as f:
    nb = nbformat.read(f, as_version=4)

client = NotebookClient(nb, timeout=600, kernel_name="python3", allow_errors=False)
client.execute()
EOF
          done

      # 5. Delete trigger file after run
      - name: Delete Trigger File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git rm colab_trigger.txt
          git commit -m "Remove trigger after workflow run"
          git push origin main
