name: Trigger Colab Notebook

on:
  push:
    paths:
      - "colab_trigger.txt"   # Only run when Pipedream updates this file

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install requests google-auth google-auth-oauthlib google-auth-httplib2

      - name: Trigger Colab Notebook
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          HUB_PAT: ${{ secrets.HUB_PAT }}
        run: |
          import os, requests, json

          # Colab notebook ID (from your URL)
          NOTEBOOK_ID = "1Oc2NdawiNabuPFTADUnDdT5cxcsusNGP"

          # GitHub commit info (just for traceability)
          headers = {
              "Authorization": f"token {os.environ['HUB_PAT']}",
              "Accept": "application/vnd.github+json"
          }

          print("📌 Triggering Colab notebook...")

          # --- OPTION A: Colab Polling ---
          # If your Colab notebook has a polling loop, just updating colab_trigger.txt is enough.
          # In that case, we don't need to call Colab API here.
          # This step is just a placeholder.

          print(f"✅ Trigger committed. Colab notebook {NOTEBOOK_ID} should pick it up via polling.")
        shell: python
