name: Trigger Colab Notebook

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - colab_trigger.txt  # Optional: can also trigger on push to this file

jobs:
  trigger-colab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Create trigger file in repo
        env:
          HUB_PAT: ${{ secrets.HUB_PAT }}  # GitHub personal access token stored as secret
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          # Create trigger file
          echo "Trigger Colab Notebook" > colab_trigger.txt
          
          git add colab_trigger.txt
          git commit -m "Add trigger for Colab notebook"
          git push https://$HUB_PAT@github.com/${GITHUB_REPOSITORY}.git main
